#@tool
#@icon(icon_path: String)
extends Node
## Documentation comments

#signal
#enum
#const

const LEVEL_0 = preload("uid://1mhb537c1qxd")
const LEVEL_1 = preload("uid://dwqw0ieu8smw7")
const LEVEL_2 = preload("uid://cdbfis58lkruf")
const LEVEL_3 = preload("uid://ccoc6j4r7yixt")


#@export var
var levels: Array[PackedScene]
var current_level: PackedScene
#@onready var

## OVERRIDES

func _ready() -> void:
	levels = [
		LEVEL_0,
		LEVEL_1,
		LEVEL_2,
		LEVEL_3
	]

#func _process(_delta: float) -> void:
	#pass


## CORE
func load_level(level_number: int) -> void:
	print_debug("Building level #%s" % level_number)
	get_tree().change_scene_to_packed(levels[level_number])


## PRIVATE/HELPER

## RECEIVERS

## SETTERS/GETTERS
