#@tool
#@icon(icon_path: String)
#class_name MyNode
extends Node2D
## Documentation comments

## signal
## enum
## const

@onready var conductor: Conductor = %Conductor
@onready var violinist: Musician = %Viol
@onready var cellist: Musician = %Cello
@onready var bassist: Musician = %Bass
#@onready var rhythm_manager: RhythmManager = %RhythmManager
#@onready var click_track: AudioStreamPlayer2D = %ClickTrack
@onready var canvas_modulate: CanvasModulate = $CanvasModulate

## OVERRIDES

func _ready() -> void:
	canvas_modulate.visible = true

func _process(_delta: float) -> void:
	pass

func _physics_process(_delta: float) -> void:
	pass

func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("ready"):
		conductor.enter_exit()
	if event.is_action_pressed("viol"):
		violinist.enter_exit()
	if event.is_action_pressed("cello"):
		cellist.enter_exit()
	if event.is_action_pressed("bass"):
		bassist.enter_exit()
## CORE
#
#func enter_instrument(instrument: Node) -> void:
	#print("Now playing " + instrument.name)
	#var instrument_audio: AudioStreamPlayer2D = instrument.get_child(0)
	#var instrument_light: PointLight2D = instrument.get_child(1)
	#instrument.play("default")
	#instrument_audio.play()
	#instrument_light.visible = true

## PRIVATE/HELPER
 
## RECEIVERS

## SETTERS/GETTERS
