#@tool
#@icon(icon_path: String)
#class_name MyNode
extends Node
## Documentation comments

#signal
#enum
#const
#@export var
#var
#@onready var
@onready var outro_stream: AudioStreamPlayer = $OutroStream

## OVERRIDES

func _ready() -> void:
	outro_stream.connect("finished", on_stream_finished)

func _process(_delta: float) -> void:
	pass

func _physics_process(_delta: float) -> void:
	pass

## CORE

## PRIVATE/HELPER

## RECEIVERS
func on_stream_finished() -> void:
	get_tree().quit()

## SETTERS/GETTERS
